package si.fri.prpo.vmesniki.soap.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekFault_Exception;
import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekRequest;
import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekResponse;
import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekeRequest;
import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekeResponse;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-12-11T13:04:24.449+01:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1", name = "izdelkiPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IzdelkiPort {

    @WebMethod(action = "http://prpo.fri.si/storitve/izdelki/v1")
    @WebResult(name = "vrniIzdelekResponse", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1", partName = "parameters")
    public VrniIzdelekResponse vrniIzdelek(
        @WebParam(partName = "parameters", name = "vrniIzdelekRequest", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1")
        VrniIzdelekRequest parameters
    ) throws VrniIzdelekFault_Exception;

    @WebMethod(action = "http://prpo.fri.si/storitve/izdelki/v1")
    @WebResult(name = "vrniIzdelekeResponse", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1", partName = "parameters")
    public VrniIzdelekeResponse vrniIzdeleke(
        @WebParam(partName = "parameters", name = "vrniIzdelekeRequest", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1")
        VrniIzdelekeRequest parameters
    );
}
