package si.fri.prpo.soap.v1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import si.fri.prpo.vmesniki.soap.v1.IzdelkiPort;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-12-11T13:04:24.579+01:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "izdelki", 
                  wsdlLocation = "file:/C:/git/skupina05/prpo-trgovina-sheme/lib/si/fri/prpo/storitve/izdelki/v1/Izdelki.wsdl",
                  targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1") 
public class Izdelki extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://prpo.fri.si/storitve/izdelki/v1", "izdelki");
    public final static QName IzdelkiSOAP = new QName("http://prpo.fri.si/storitve/izdelki/v1", "izdelkiSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/git/skupina05/prpo-trgovina-sheme/lib/si/fri/prpo/storitve/izdelki/v1/Izdelki.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Izdelki.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/git/skupina05/prpo-trgovina-sheme/lib/si/fri/prpo/storitve/izdelki/v1/Izdelki.wsdl");
        }
        WSDL_LOCATION = url;
        System.out.println("WSDLLLLLLLLLLLLLLLLLLLLLLLLLLLL");
        System.out.println(WSDL_LOCATION.toString());
    }

    public Izdelki(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Izdelki(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Izdelki() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Izdelki(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Izdelki(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Izdelki(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IzdelkiPort
     */
    @WebEndpoint(name = "izdelkiSOAP")
    public IzdelkiPort getIzdelkiSOAP() {
        return super.getPort(IzdelkiSOAP, IzdelkiPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IzdelkiPort
     */
    @WebEndpoint(name = "izdelkiSOAP")
    public IzdelkiPort getIzdelkiSOAP(WebServiceFeature... features) {
        return super.getPort(IzdelkiSOAP, IzdelkiPort.class, features);
    }

}
