
package si.fri.prpo.sheme.izdelki.sporocila.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-12-11T13:04:24.344+01:00
 * Generated source version: 3.0.5
 */

@WebFault(name = "vrniIzdelekFault", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1")
public class VrniIzdelekFault_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekFault vrniIzdelekFault;

    public VrniIzdelekFault_Exception() {
        super();
    }
    
    public VrniIzdelekFault_Exception(String message) {
        super(message);
    }
    
    public VrniIzdelekFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public VrniIzdelekFault_Exception(String message, si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekFault vrniIzdelekFault) {
        super(message);
        this.vrniIzdelekFault = vrniIzdelekFault;
    }

    public VrniIzdelekFault_Exception(String message, si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekFault vrniIzdelekFault, Throwable cause) {
        super(message, cause);
        this.vrniIzdelekFault = vrniIzdelekFault;
    }

    public si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekFault getFaultInfo() {
        return this.vrniIzdelekFault;
    }
}
